### model
model_name_or_path: ../ckpts/Llama-3-8B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: air-64
template: llama3
cutoff_len: 2048
max_samples: 64
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/llama3
logging_steps: 5
save_steps: 10
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: wandb
run_name: llama3 

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 50.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
ddp_timeout: 180000000
resume_from_checkpoint: null
bf16: true

## eval
eval_dataset: mix-10
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 5